site:
  title: Camel K
  url: https://www.nicolaferraro.me/website-experiments
  start_page: camel-k::getting-started.adoc 
content:
  sources:
  - url: git@github.com:nicolaferraro/camel-k.git
    branches:
    - antora
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  output_dir: assets
output:
  dir: ./docs